### ISSUE TITLE
Enhancement request: Show calendar entries as "Out of Office"

### ISSUE THREAD

**Issue by mousaka20** [mbeer/OutlookSwissPTTimetable#2]
Thanks for this Outlook plugin. 

It would be even more helpful, if the calendar entries are set as "Out of Office", or even better to give the user the option to define  the "show as" setting during "xxreise eintragen".

**Comment by mbeer** [comment]
I’d rather not display another dialog for choosing the [BusyStatus](https://docs.microsoft.com/en-us/office/vba/api/outlook.olbusystatus) of the appointment during “An-/Rückreise eintragen”. However, I could imagine adding this choice to the settings dialog. So every user can configure OutlookSwissPTTimetable to apply the option he/she likes most.

**Comment by mousaka20** [comment]
That is a good proposal as well, as probably most user will use the same settings for similar calendar entries.
