### ISSUE TITLE
Lädt keine Verbindungen

### ISSUE THREAD

**Issue by rahelryf** [mbeer/OutlookSwissPTTimetable#3]
Hallo
Dein Tool ist super. Leider funktioniert es nicht immer. Die Verbindungen werden gelegentlich nicht geladen. Der Loader erscheint und nichts geschieht. Beispiel in der Beilage. 
LG Rahel
![bug](https://user-images.githubusercontent.com/24652080/51829495-ed93f100-22ed-11e9-8114-55e8d20a237f.JPG)

**Comment by mbeer** [comment]
@rahelryf 
Das Problem dürfte daran liegen, dass du keinen Zielort eingegeben hast (Eingabe-/Auswahlfeld unterhalb von «Zürich» ist leer). Ich werde in der nächsten Version eine entsprechende Fehlermeldung einbauen.

**Comment by rahelryf** [comment]
Vielen Dank!!!

Von: Michael Beer <notifications@github.com>
Gesendet: Montag, 28. Januar 2019 14:00
An: mbeer/OutlookSwissPTTimetable <OutlookSwissPTTimetable@noreply.github.com>
Cc: Ryf Rahel (I-FN-SUN-IS) <rahel.ryf@sbb.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [mbeer/OutlookSwissPTTimetable] Lädt keine Verbindungen (#3)


@rahelryf<https://github.com/rahelryf>
Das Problem dürfte daran liegen, dass du keinen Zielort eingegeben hast (Eingabe-/Auswahlfeld unterhalb von «Zürich» ist leer). Ich werde in der nächsten Version eine entsprechende Fehlermeldung einbauen.
