### ISSUE TITLE
Kompatiblität Outlook 365

### ISSUE THREAD

**Issue by rokdd** [mbeer/OutlookSwissPTTimetable#6]
Kann es sein, dass unter Outlook 365 das Addin leider nicht funktioniert? Es wird zwar in der Liste angezeigt, aber die Ribbons erscheinen nie. Oder gibt es einen Trick wie man diese aktivieren kann? (oder etwas falsch machen)?

**Comment by mbeer** [comment]
Nein, das sollte nicht ein generelles Problem bei Outlook 365 sein. Bei mir funktioniert das Addin beispielsweise unter Microsoft® Outlook® für Microsoft 365 MSO (Version 2206 Build 16.0.15330.20144) 64 Bit einwandfrei.
